import 'package:flutter/material.dart';
import 'package:hvac_calc/information_text_converting.dart';
import 'package:hvac_calc/screens/about_the_calculation.dart';
import 'main.dart';

Widget informationTextSi () {
  return Column(
    children: [
      myVerticalOffset(10),
      myBlueHeadline('Pressure, kPa'),
      myFormula(r'p = 101.325(1-2.25577 \times 10^{-5}Z)^{5.2559}', '3'),
      mySimpleLeftText('where'),
      myFormulaWhere(r'Z\:-\:', 'altitude, m'),
      myVerticalOffset(10),
      
      // Branch #1 Initial data - dry-bulb temperature and wet-bulb temperature

      ListTileTheme(
        minLeadingWidth: 0,
        child: ExpansionTile(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
          collapsedShape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
          childrenPadding: const EdgeInsets.symmetric(vertical: 10),
          collapsedTextColor: AppTheme.colors.font1,
          tilePadding: const EdgeInsets.only(left: 10, right: 10),
          leading: const Icon(
            Icons.info_outline,
            size: 20,
          ),
          collapsedIconColor: AppTheme.colors.font1,
          collapsedBackgroundColor: AppTheme.colors.toggle,
          expandedAlignment: Alignment.centerLeft,
          title: const Text(
            'Initial data - dry-bulb temperature and wet-bulb temperature',
            style: TextStyle(
              fontSize: 14,
            ),
          ),
          children: [
            myBlueHeadlineSub('Water vapor saturation pressure Pws, Pa'),
            mySimpleJustifyText(
              '\t\t\tThe water vapor saturation pressure is required to determine '
              'a number of moist air properties, principally the saturation humidity '
              'ratio. Values may be calculated from '
              'formulas given by IPAWS R7-97(2012) and R14-08 (2011).\n'
              '\t\t\tThe saturation (sublimation) pressure over ice for the temperature '
              'range of -100 to 0°C is given by'
            ),
            myFormula(r'\mathrm{ln\:}p_{ws}=C_1/T+C_2+C_3T+C_4T^2+C_5T^3+C_6T^4+C_7\:{ln\:}T', '5'),
            mySimpleLeftText('where'),
            myFormulaLeft(r'C_1=-5.6745359\:\mathrm{E}\text{+}03'),
            myFormulaLeft(r'C_2=6.3925247\:\mathrm{E}\text{+}00'),
            myFormulaLeft(r'C_3=-9.6778430\:\mathrm{E}\text{-}03'),
            myFormulaLeft(r'C_4=6.2215701\:\mathrm{E}\text{-}07'),
            myFormulaLeft(r'C_5=2.0747825\:\mathrm{E}\text{-}09'),
            myFormulaLeft(r'C_6=-9.4840240\:\mathrm{E}\text{-}13'),
            myFormulaLeft(r'C_7=4.1635019\:\mathrm{E}\text{+}00'),
            mySimpleJustifyText(
              '\t\t\tThe saturation pressure over liquid water for the '
              'temperature range of 0 to 200°С is given by'
            ),
            myFormula(r'\mathrm{ln\:}p_{ws}=C_8/T+C_9+C_{10}T+C_{11}T^2+C_{12}T^3+C_{13}\:{ln\:}T', '6'),
            mySimpleLeftText('where'),
            myFormulaLeft(r'C_8=-5.8002206\:\mathrm{E}\text{+}03'),
            myFormulaLeft(r'C_9=1.3914993\:\mathrm{E}\text{+}00'),
            myFormulaLeft(r'C_{10}=-4.8640239\:\mathrm{E}\text{-}02'),
            myFormulaLeft(r'C_{11}=4.1764768\:\mathrm{E}\text{-}05'),
            myFormulaLeft(r'C_{12}=-1.4452093\:\mathrm{E}\text{-}08'),
            myFormulaLeft(r'C_{13}=6.5459673\:\mathrm{E}\text{+}00'),
            myFormulaWhere(r'T\:-\:', 'absolute temperature, K = °C + 273.15'),
            myBlueHeadlineSub('Saturation humidity ratio Ws, kgw/kgda'),
            myFormula(r'W_S=0.621945\frac{p_{ws}}{p-p_{ws}}', '21'),
            mySimpleLeftText('where'),
            myFormulaWhere(r'p\:-\:', 'barometric pressure of atmospheric air, Pa (Formula 3 ASHRAE 2021)'),
            myFormulaWhere(r'p_{ws}\:-\:', 'water vapor saturation pressure, Pa (Formulas 5 and 6 ASHRAE 2021)'),
            myBlueHeadlineSub('Humidity ratio W, kgw/kgda'),
            myFormula(r'W=\frac{(2501-2.326t^*)W_s^*-1.006(t-t^*)}{2501+1.86t-4.186t^*}', '33'),
            mySimpleLeftText('where'),
            myFormulaWhere(r't^*\:-\:', 'thermodynamic wet-bulb temperature, °C'),
            myFormulaWhere(r't\:-\:', 'thermodynamic dry-bulb temperature, °C'),
            myFormulaWhereSub(r'W_s^*\:-\:', 'saturation humidity ratio Ws at a wet-bulb temperature t*, kgw/kgda (Formula 21 ASHRAE 2021)'),
            myBlueHeadlineSub('Partial pressure of water vapor Pw, Pa'),
            myFormula(r'W=0.621945\frac{p_w}{p-p_w}', '20'),
            myFormulaWithoutAshrae(r'p_w=\frac{W \times p}{0.621945+W}', '1'),
            mySimpleLeftText('where'),
            myFormulaWhere(r'p\:-\:', 'barometric pressure of atmospheric air, Pa (Formula 3 ASHRAE 2021)'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio, kgw/kgda(Formula 33 ASHRAE 2021)'),
            myBlueHeadlineSub('Relative humidity ϕ'),
            myFormula(r'\phi=(p_{wv-enh}/p_{wvs-ref}|_{p,t})=[f(p,t_{dp})e(t_{dp})]/[f(p,t_{db})e(t_{db})]', '12'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'p_{wv-enh}\:-\:', 'actual water vapor partial pressure in moist air at the dew-point pressure and temperature, Pa (Formula 1)'),
            myFormulaWhereSub(r'p_{wvs-ref}\:-\:', 'reference saturation water vapor partial pressure at the dry-bulb pressure and temperature, Pa (Formulas 5 and 6 ASHRAE 2021)'),
            myBlueHeadlineSub('Dew point temperature td, °C'),
            mySimpleLeftText('Between dew points of 0 and 93°C,'),
            myFormula(r't_d=C_{14}+C_{15}\alpha+C_{16}\alpha^2+C_{17}\alpha^3+C_{18}(p_w)^{0.1984}', '37'),
            mySimpleLeftText('Below 0°C,'),
            myFormula(r't_d=6.09+12.608\alpha+0.4959\alpha^2', '38'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'\alpha\:-\:', 'ln pw'),
            myFormulaWhereSub(r'p_w\:-\:', 'water vapor partial pressure, kPa (Formula 1)'),
            myFormulaLeft(r'C_{14}=6.54'),
            myFormulaLeft(r'C_{15}=14.526'),
            myFormulaLeft(r'C_{16}=0.7389'),
            myFormulaLeft(r'C_{17}=0.09486'),
            myFormulaLeft(r'C_{18}=0.4569'),
            myBlueHeadlineSub('Moist air specific enthalpy h, kJ/kgda'),
            myFormula(r'h=1.006t+W(2501+1.86t)', '30'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio, kgw/kgda (Formula 33 ASHRAE 2021)'),
            myFormulaWhereSub(r't\:-\:', 'thermodynamic dry-bulb temperature, °C'),
            myBlueHeadlineSub('Specific volume v, m3/kgda'),
            myFormula(r'v=0.287042(t+273.15)(1+1.607858W)/p', '26'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio, kgw/kgda (Formula 33 ASHRAE 2021)'),
            myFormulaWhereSub(r't\:-\:', 'thermodynamic dry-bulb temperature, °C'),
            myFormulaWhereSub(r'p\:-\:', 'barometric pressure of atmospheric air, Pa (Formula 3 ASHRAE 2021)'),
            myBlueHeadline('Degree of saturation'),
            myFormula(r'\mu=\frac{W}{W_s}', '23'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio, kgw/kgda (Formula 33 ASHRAE 2021)'),
            myFormulaWhereSub(r'W_s\:-\:', 'saturation humidity ratio at a dry-bulb temperature, kgw/kgda (Formula 21 ASHRAE 2021)'),
          ],
        ),
      ),
      myVerticalOffset(10),

      // Branch #2 Initial data - dry-bulb temperature and dew point temperature
    
      ListTileTheme(
        minLeadingWidth: 0,
        child: ExpansionTile(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
          collapsedShape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
          childrenPadding: const EdgeInsets.symmetric(vertical: 10),
          collapsedTextColor: AppTheme.colors.font1,
          tilePadding: const EdgeInsets.only(left: 10, right: 10),
          leading: const Icon(
            Icons.info_outline,
            size: 20,
          ),
          collapsedIconColor: AppTheme.colors.font1,
          collapsedBackgroundColor: AppTheme.colors.toggle,
          expandedAlignment: Alignment.centerLeft,
          title: const Text(
            'Initial data - dry-bulb temperature and dew point temperature',
            style: TextStyle(
              fontSize: 14,
            ),
          ),
          children: [
            myBlueHeadlineSub('Water vapor saturation pressure Pws, Pa'),
            mySimpleJustifyText(
              '\t\t\tThe water vapor saturation pressure is required to determine '
              'a number of moist air properties, principally the saturation humidity '
              'ratio. Values may be calculated from '
              'formulas given by IPAWS R7-97(2012) and R14-08 (2011).\n'
              '\t\t\tThe saturation (sublimation) pressure over ice for the temperature '
              'range of -100 to 0°C is given by'
            ),
            myFormula(r'\mathrm{ln\:}p_{ws}=C_1/T+C_2+C_3T+C_4T^2+C_5T^3+C_6T^4+C_7\:{ln\:}T', '5'),
            mySimpleLeftText('where'),
            myFormulaLeft(r'C_1=-5.6745359\:\mathrm{E}\text{+}03'),
            myFormulaLeft(r'C_2=6.3925247\:\mathrm{E}\text{+}00'),
            myFormulaLeft(r'C_3=-9.6778430\:\mathrm{E}\text{-}03'),
            myFormulaLeft(r'C_4=6.2215701\:\mathrm{E}\text{-}07'),
            myFormulaLeft(r'C_5=2.0747825\:\mathrm{E}\text{-}09'),
            myFormulaLeft(r'C_6=-9.4840240\:\mathrm{E}\text{-}13'),
            myFormulaLeft(r'C_7=4.1635019\:\mathrm{E}\text{+}00'),
            mySimpleJustifyText(
              '\t\t\tThe saturation pressure over liquid water for the'
              'temperature range of 0 to 200°С is given by'
            ),
            myFormula(r'\mathrm{ln\:}p_{ws}=C_8/T+C_9+C_{10}T+C_{11}T^2+C_{12}T^3+C_{13}\:{ln\:}T', '6'),
            mySimpleLeftText('where'),
            myFormulaLeft(r'C_8=-5.8002206\:\mathrm{E}\text{+}03'),
            myFormulaLeft(r'C_9=1.3914993\:\mathrm{E}\text{+}00'),
            myFormulaLeft(r'C_{10}=-4.8640239\:\mathrm{E}\text{-}02'),
            myFormulaLeft(r'C_{11}=4.1764768\:\mathrm{E}\text{-}05'),
            myFormulaLeft(r'C_{12}=-1.4452093\:\mathrm{E}\text{-}08'),
            myFormulaLeft(r'C_{13}=6.5459673\:\mathrm{E}\text{+}00'),
            myFormulaWhere(r'T\:-\:', 'absolute temperature, K = °C + 273.15'),             
            myBlueHeadlineSub('Humidity ratio W, kgw/kgda'),
            myFormula(r'W=0.621945\frac{p_w}{p-p_w}', '20'),
            mySimpleLeftText('where'),
            myFormulaWhere(r'p\:-\:', 'barometric pressure of atmospheric air, Pa (Formula 3 ASHRAE 2021)'),
            myFormulaWhere(r'p_w\:-\:', 'water vapor partial pressure at a dew point temperature, Pa (Formulas 5 and 6 ASHRAE 2021 )'),
            myBlueHeadlineSub('Saturation humidity ratio Ws, kgw/kgda'),
            myFormula(r'W_S=0.621945\frac{p_{ws}}{p-p_{ws}}', '21'),
            mySimpleLeftText('where'),
            myFormulaWhere(r'p\:-\:', 'barometric pressure of atmospheric air, Pa (Formula 3 ASHRAE 2021)'),
            myFormulaWhere(r'p_{ws}\:-\:', 'water vapor saturation pressure, Pa (Formulas 5 and 6 ASHRAE 2021)'),
            myBlueHeadlineSub('Wet bulb temperature td, °C'),
            mySimpleLeftText('Solution of equation 33 by iteration method'),
            myFormula(r'W=\frac{(2501-2.326t^*)W_s^*-1.006(t-t^*)}{2501+1.86t-4.186t^*}', '33'),
            mySimpleLeftText('where'),
            myFormulaWhere(r't^*\:-\:', 'thermodynamic wet-bulb temperature, °C'),
            myFormulaWhere(r't\:-\:', 'thermodynamic dry-bulb temperature, °C'),
            myFormulaWhereSub(r'W_s^*\:-\:', 'saturation humidity ratio Ws at a wet-bulb temperature t*, kgw/kgda (Formula 21 ASHRAE 2021)'),
            myVerticalOffset(10),
            mySimpleLeftTextHead('Algorithm:'),
            mySimpleLeftText('td - lower limit, tdb - upper limit'),
            mySimpleLeftText('1) twb = (lower limit + upper limit) / 2'),
            mySimpleLeftText('2) calculate Ws (Formula 33 ASHRAE 2021)'),
            mySimpleLeftText('3) if Ws > W -> upper limit = twb, if Ws <= W -> lower limit = twb'),
            mySimpleLeftText('4) back to step 1 as long as the difference between the lower and upper limit is greater than 0.001'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio, kgw/kgda (Formula 20 ASHRAE 2021)'),
            myFormulaWhereSub(r'W_s\:-\:', 'humidity ratio, kgw/kgda (Formula 33 ASHRAE 2021)'),
            myFormulaWhere(r't_d\:-\:', 'dew-point temperature, °C'),
            myFormulaWhere(r't_{wb}\:-\:', 'thermodynamic wet-bulb temperature, °C'),
            myBlueHeadlineSub('Relative humidity ϕ'),
            myFormula(r'\phi=(p_{wv-enh}/p_{wvs-ref}|_{p,t})=[f(p,t_{dp})e(t_{dp})]/[f(p,t_{db})e(t_{db})]', '12'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'p_{wv-enh}\:-\:', 'actual water vapor partial pressure in moist air at the dew-point pressure and temperature, Pa (Formulas 5 and 6 ASHRAE 2021)'),
            myFormulaWhereSub(r'p_{wvs-ref}\:-\:', 'reference saturation water vapor partial pressure at the dry-bulb pressure and temperature, Pa (Formulas 5 and 6 ASHRAE 2021)'),
            myBlueHeadlineSub('Moist air specific enthalpy h, kJ/kgda'),
            myFormula(r'h=1.006t+W(2501+1.86t)', '30'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio, kgw/kgda (Formula 33 ASHRAE 2021)'),
            myFormulaWhereSub(r't\:-\:', 'thermodynamic dry-bulb temperature, °C'),
            myBlueHeadlineSub('Specific volume v, m3/kgda'),
            myFormula(r'v=0.287042(t+273.15)(1+1.607858W)/p', '26'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio, kgw/kgda (Formula 33 ASHRAE 2021)'),
            myFormulaWhereSub(r't\:-\:', 'thermodynamic dry-bulb temperature, °C'),
            myFormulaWhereSub(r'p\:-\:', 'barometric pressure of atmospheric air, Pa (Formula 3 ASHRAE 2021)'),
            myBlueHeadline('Degree of saturation'),
            myFormula(r'\mu=\frac{W}{W_s}', '23'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio, kgw/kgda (Formula 33 ASHRAE 2021)'),
            myFormulaWhereSub(r'W_s\:-\:', 'saturation humidity ratio at a dry-bulb temperature, kgw/kgda (Formula 21 ASHRAE 2021)'),
          ],
        ),
      ),
      myVerticalOffset(10),

      // Branch #3 Initial data - dry-bulb temperature and relative humidity

      ListTileTheme(
        minLeadingWidth: 0,
        child: ExpansionTile(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
          collapsedShape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
          childrenPadding: const EdgeInsets.symmetric(vertical: 10),
          collapsedTextColor: AppTheme.colors.font1,
          tilePadding: const EdgeInsets.only(left: 10, right: 10),
          leading: const Icon(
            Icons.info_outline,
            size: 20,
          ),
          collapsedIconColor: AppTheme.colors.font1,
          collapsedBackgroundColor: AppTheme.colors.toggle,
          expandedAlignment: Alignment.centerLeft,
          title: const Text(
            'Initial data - dry-bulb temperature and relative humidity',
            style: TextStyle(
              fontSize: 14,
            ),
          ),
          children: [
            myBlueHeadlineSub('Water vapor saturation pressure Pws, Pa'),
            mySimpleJustifyText(
              '\t\t\tThe water vapor saturation pressure is required to determine '
              'a number of moist air properties, principally the saturation humidity '
              'ratio. Values may be calculated from '
              'formulas given by IPAWS R7-97(2012) and R14-08 (2011).\n'
              '\t\t\tThe saturation (sublimation) pressure over ice for the temperature '
              'range of -100 to 0°C is given by'
            ),
            myFormula(r'\mathrm{ln\:}p_{ws}=C_1/T+C_2+C_3T+C_4T^2+C_5T^3+C_6T^4+C_7\:{ln\:}T', '5'),
            mySimpleLeftText('where'),
            myFormulaLeft(r'C_1=-5.6745359\:\mathrm{E}\text{+}03'),
            myFormulaLeft(r'C_2=6.3925247\:\mathrm{E}\text{+}00'),
            myFormulaLeft(r'C_3=-9.6778430\:\mathrm{E}\text{-}03'),
            myFormulaLeft(r'C_4=6.2215701\:\mathrm{E}\text{-}07'),
            myFormulaLeft(r'C_5=2.0747825\:\mathrm{E}\text{-}09'),
            myFormulaLeft(r'C_6=-9.4840240\:\mathrm{E}\text{-}13'),
            myFormulaLeft(r'C_7=4.1635019\:\mathrm{E}\text{+}00'),
            mySimpleJustifyText(
              '\t\t\tThe saturation pressure over liquid water for the '
              'temperature range of 0 to 200°С is given by'
            ),
            myFormula(r'\mathrm{ln\:}p_{ws}=C_8/T+C_9+C_{10}T+C_{11}T^2+C_{12}T^3+C_{13}\:{ln\:}T', '6'),
            mySimpleLeftText('where'),
            myFormulaLeft(r'C_8=-5.8002206\:\mathrm{E}\text{+}03'),
            myFormulaLeft(r'C_9=1.3914993\:\mathrm{E}\text{+}00'),
            myFormulaLeft(r'C_{10}=-4.8640239\:\mathrm{E}\text{-}02'),
            myFormulaLeft(r'C_{11}=4.1764768\:\mathrm{E}\text{-}05'),
            myFormulaLeft(r'C_{12}=-1.4452093\:\mathrm{E}\text{-}08'),
            myFormulaLeft(r'C_{13}=6.5459673\:\mathrm{E}\text{+}00'),
            myFormulaWhere(r'T\:-\:', 'absolute temperature, K = °C + 273.15'),
            myBlueHeadlineSub('Saturation pressure of water vapor\nin the absence of air Pw, Pa'),
            myFormula(r'\phi=(p_{wv-enh}/p_{wvs-ref}|_{p,t})=[f(p,t_{dp})e(t_{dp})]/[f(p,t_{db})e(t_{db})]', '12'),
            myFormulaWithoutAshrae(r'p_w=\phi \times p_{ws}', '1'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'\phi\:-\:', 'relative humidity'),
            myFormulaWhereSub(r'p_{ws}\:-\:', 'water vapor saturation pressure at a dry bulb temperature, Pa (Formulas 5 and 6 ASHRAE 2021 )'),
            myBlueHeadlineSub('Humidity ratio W, kgw/kgda'),
            myFormula(r'W=0.621945\frac{p_w}{p-p_w}', '20'),
            mySimpleLeftText('where'),
            myFormulaWhere(r'p\:-\:', 'barometric pressure of atmospheric air, Pa (Formula 3 ASHRAE 2021)'),
            myFormulaWhere(r'p_w\:-\:', 'partial pressure of water vapor, Pa (Formula 1)'),
            myBlueHeadlineSub('Dew point temperature td, °C'),
            mySimpleLeftText('Between dew points of 0 and 93°C,'),
            myFormula(r't_d=C_{14}+C_{15}\alpha+C_{16}\alpha^2+C_{17}\alpha^3+C_{18}(p_w)^{0.1984}', '37'),
            mySimpleLeftText('Below 0°C,'),
            myFormula(r't_d=6.09+12.608\alpha+0.4959\alpha^2', '38'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'\alpha\:-\:', 'ln pw'),
            myFormulaWhereSub(r'p_w\:-\:', 'water vapor partial pressure, kPa (Formula 1)'),
            myFormulaLeft(r'C_{14}=6.54'),
            myFormulaLeft(r'C_{15}=14.526'),
            myFormulaLeft(r'C_{16}=0.7389'),
            myFormulaLeft(r'C_{17}=0.09486'),
            myFormulaLeft(r'C_{18}=0.4569'),
            myBlueHeadlineSub('Saturation humidity ratio Ws, kgw/kgda'),
            myFormula(r'W_S=0.621945\frac{p_{ws}}{p-p_{ws}}', '21'),
            mySimpleLeftText('where'),
            myFormulaWhere(r'p\:-\:', 'barometric pressure of atmospheric air, Pa (Formula 3 ASHRAE 2021)'),
            myFormulaWhere(r'p_{ws}\:-\:', 'water vapor saturation pressure, Pa (Formulas 5 and 6 ASHRAE 2021)'),
            myBlueHeadlineSub('Wet bulb temperature td, °C'),
            mySimpleLeftText('Solution of equation 33 by iteration method'),
            myFormula(r'W=\frac{(2501-2.326t^*)W_s^*-1.006(t-t^*)}{2501+1.86t-4.186t^*}', '33'),
            mySimpleLeftText('where'),
            myFormulaWhere(r't^*\:-\:', 'thermodynamic wet-bulb temperature, °C'),
            myFormulaWhere(r't\:-\:', 'thermodynamic dry-bulb temperature, °C'),
            myFormulaWhereSub(r'W_s^*\:-\:', 'saturation humidity ratio Ws at a wet-bulb temperature t*, kgw/kgda (Formula 21 ASHRAE 2021)'),
            myVerticalOffset(10),
            mySimpleLeftTextHead('Algorithm:'),
            mySimpleLeftText('td - lower limit, tdb - upper limit'),
            mySimpleLeftText('1) twb = (lower limit + upper limit) / 2'),
            mySimpleLeftText('2) calculate Ws (Formula 33 ASHRAE 2021)'),
            mySimpleLeftText('3) if Ws > W -> upper limit = twb, if Ws <= W -> lower limit = twb'),
            mySimpleLeftText('4) back to step 1 as long as the difference between the lower and upper limit is greater than 0.001'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio , kgw/kgda (Formula 20 ASHRAE 2021)'),
            myFormulaWhereSub(r'W_s\:-\:', 'humidity ratio , kgw/kgda (Formula 33 ASHRAE 2021)'),
            myFormulaWhere(r't_d\:-\:', 'dew-point temperature , °C'),
            myFormulaWhere(r't_{wb}\:-\:', 'thermodynamic wet-bulb temperature, °C'),
            myBlueHeadlineSub('Moist air specific enthalpy h, kJ/kgda'),
            myFormula(r'h=1.006t+W(2501+1.86t)', '30'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio, kgw/kgda (Formula 33 ASHRAE 2021)'),
            myFormulaWhereSub(r't\:-\:', 'thermodynamic dry-bulb temperature, °C'),
            myBlueHeadlineSub('Specific volume v, m3/kgda'),
            myFormula(r'v=0.287042(t+273.15)(1+1.607858W)/p', '26'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio, kgw/kgda (Formula 33 ASHRAE 2021)'),
            myFormulaWhereSub(r't\:-\:', 'thermodynamic dry-bulb temperature, °C'),
            myFormulaWhereSub(r'p\:-\:', 'barometric pressure of atmospheric air, Pa (Formula 3 ASHRAE 2021)'),
            myBlueHeadline('Degree of saturation'),
            myFormula(r'\mu=\frac{W}{W_s}', '23'),
            mySimpleLeftText('where'),
            myFormulaWhereSub(r'W\:-\:', 'humidity ratio, kgw/kgda (Formula 33 ASHRAE 2021)'),
            myFormulaWhereSub(r'W_s\:-\:', 'saturation humidity ratio at a dry-bulb temperature, kgw/kgda (Formula 21 ASHRAE 2021)'),
          ],
        ),
      ),
      myVerticalOffset(10),
      informationTextConv(),    // Text from information_text_converting.dart
    ],
  );
}